### PR TITLE
mods

### PR DESCRIPTION
**Pull request by cpu010100**
I made some changes, please review.

### CODE REVIEW

**Comment by mikew** [comment]
great! will review over the weekend

**Comment by gddeen** [comment]
This is  a test of some of the features of cpu010100 new features.
I can test a lot by checking Windows 7, 8, OSX and linux if anyone is interested.

I assume the added features are:
- Be nice when download directory is unknown???
- Add Download all feature to avoid having to click each new show for a Favorite.
- Add Watch All for a TV show???

Test 1: (Not really happy with results) 
On MAC OSX PMS Server, ss-plex.bundle from Safari.
I deleted all “TV Shows” libraries.  The destination for a “tv show” is now unknown.
I went to ss-plex, “Information” button and get message “This Channel is not responding.”

I went to a saved “Favorite” for a “TV Show” when had 2 shows in it and selected "Download All”
button.  

NOTE: One of the episodes was highlighted as already have being downloaded. (Library was just deleted…)
It stated “Added 1 of 2.”

Probably both should have been added to the download queue. I will see what didn’t get refreshed when I
deleted the library. 

The downloaded file went where?

Test 2: (Passed)
- (passed) Download All feature for TV Shows favorite on Mac OSX from Safari.
  
  2 downloadable shows with multiple folders also in the list were found from a TV Show “Favorites” list.

I selected “Download All” and all the shows were queued and downloaded correctly.

Test 3: (Not run yet)
- Download All feature for TV Shows favorite on Windows 7

Test 4: (Not run yet)
- PLEX Roku Setup unknown tv show library destination from Mac OSX

Test 5: (Not run yet)
- Mac OSX Setup unknown Movie library destination

Test 6: (Not run yet)
- Nothing new in favorite list to download. Select 'download all’

Test 7: (Not run yet)
- See if interfaces remain consistent across Roku/Safari

**Comment by cpu010100** [comment]
In regards to the download all button, it'll only download episodes that haven't been downloaded before, and in the current directory of the button.  The database of what has been downloaded is not tied to the plex libraries.

The recent releases download button only downloads content which has been downloaded before also.  So if you have abcd show as a favorite, but haven't ever downloaded it, because perhaps you stream it.  when u click the download but the abcd show will be skipped.

**Comment by mikew** [comment]
@cpu010100 would you be able to write tests for these features?

**Comment by cpu010100** [comment]
@mikew not really sure how to begin, they are user triggered actions.  I'm a NOOB at python and mostly have been just moving the code around until it works.  There is a bug with attempting to queue a ton of stuff, at least on firefox 32bit.  I think the url just got too long for the browser to handle.  I'm testing the fix for that in my testing fork.

**Comment by mikew** [comment]
Cool. We should talk via email so I can get a better understanding of the
new features. I've been playing with it but can't really understand the new
item in the main menu.
- Mike Wyatt

**Comment by cpu010100** [comment]
@mikew Emails good for me, you should have received mine by now.  Just added the ability to download more then one thing at a time in my testing fork, it's a WIP, but appears to work.  I saw the testing cases, I'll check that out once I clean up the latest code.

**Pull request closed without merging**
